def usage():
    print("Welcome to AFGI: Augmented Formal Graphical Interface!\n")
    print("Usage:")
    print("afgi [Optional] Mandatory parameters")
    print("\n")
    print("Mandatory:")
    print("-t, --tcl                   TCL file") 
    print("-c, --config                 Configuration required to locate (or generate) formal-friendly filelist")
    print("-m, --module                 Top module name of the design")
    print("-l, --link                   VLNV link of the design")
    print("-b, --bind_file              Bind file for binding DUT with a bus wrapper, generic, AXI, APB, or AHB")
    print("-v, --view                   View name for bootenv") 
    print("\n")
    print("Optional:")
    print("-h, --help                   Displays this message")
    print("-t, --test                   Formal test name")
    print("-V, --Version                Output version information")